sudo: required

language: php
php:
  - "5.4"

branches:
  only:
    - master

before_script:
  - curl -V
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod a+x phing-latest.phar
 
script:
  - php phing-latest.phar
  
after_script:
  - ls -al
  - cd build
  - ls -al

notifications:
  email: false
