language: php
php:
  - "5.4"

before_script:
  - wget https://getcomposer.org/composer.phar
  - chmod +x composer.phar
  - php composer.phar install
 
script:
  - google-chrome --version
  - firefox --version
  - php bin/selenium-setup.php selfTest
  
after_script:
  - cat build/logs/selenium.log

notifications:
  email: false
