language: php
php:
  - "5.4"

before_script:
  - chmod +x bin/commands/linux/start_selenium.sh
  - php bin/selenium-setup.php start
 
script:
  - ./bin/commands/linux/start_phpunit_tests.sh

after_script:
  - ls -al
  - cd build
  - ls -al
  - cat logs/selenium.log

notifications:
  email: false
