language: php
php:
  - "5.4"

branches:
  only:
    - master

before_script:
  - sudo apt-get install xvfb
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 10
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod +x phing-latest.phar
 
script:
  - php phing-latest.phar -Dselenium.server.port=8111
  
after_script:
  - ls -al
  - cd build
  - ls -al

notifications:
  email: false
