language: php

os:
  - linux

php:
  - "5.4"

before_script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - composer self-update
  - composer install
 
script:
  - google-chrome --version
  - firefox --version
  - php selenium-setup start-server
  - mkdir tests; cd tests
  - wget https://raw.githubusercontent.com/bogdananton/Selenium-Setup-VM/master/tests/composer.json
  - wget https://raw.githubusercontent.com/bogdananton/Selenium-Setup-VM/master/tests/test.php
  - composer update
  - phpunit test.php
  
after_script:
  - cat build/logs/selenium.log

notifications:
  email: false
  irc:
    channels:
      - "asimov.freenode.net#mobiledetect"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo}. Build details: %{build_url}"
