language: php
php:
  - "5.4"

before_script:
  - apt-get install phantomjs xvfb # @todo move phantomjs into dependencies / installer
  - composer install --dev --no-interaction
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 10 # give xvfb some time to start
  - mkdir build && mkdir build/logs && touch build/logs/selenium.log

script:
  - php bin/selenium-setup.php start
  - chmod +x bin/commands/linux/start_phpunit_tests.sh
  - testsuite="headless" seleniumServerHost=localhost seleniumServerPort=4444 ./bin/commands/linux/start_phpunit_tests.sh

after_script:
  - ls -al
  - cd build && ls -al
  - cat logs/selenium.log

notifications:
  email: false
