language: php
php:
  - "5.4"

before_script:
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod +x phing-latest.phar
 
script:
  - php phing-latest.phar -Dselenium.server.port=8111
  
after_script:
  - ls -al
  - cd build
  - ls -al

notifications:
  email: false
